
from PyQt5.QtGui import QMovie, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1078)
        MainWindow.setStyleSheet(";background-image: url(../pythonProject/audio/10.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.first = QtWidgets.QPushButton(self.centralwidget)
        self.first.setGeometry(QtCore.QRect(1020, 700, 461, 151))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.first.setFont(font)
        self.first.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.first.setStyleSheet(" background-color:rgb(106, 105, 118); color:rgb(191, 190, 201);border-radius:20px ;border: 10px groove gray;border-style: outset"
"")
        self.first.setObjectName("first")
        self.second = QtWidgets.QPushButton(self.centralwidget)
        self.second.setGeometry(QtCore.QRect(1020, 900, 461, 151))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.second.setFont(font)
        self.second.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.second.setStyleSheet(" background-color:rgb(106, 105, 118); color:rgb(191, 190, 201);border-radius:20px ;border: 10px groove gray;border-style: outset"
"")
        self.second.setObjectName("second")
        self.third = QtWidgets.QPushButton(self.centralwidget)
        self.third.setGeometry(QtCore.QRect(440, 900, 481, 151))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.third.setFont(font)
        self.third.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.third.setStyleSheet(" background-color:rgb(106, 105, 118); color:rgb(191, 190, 201);border-radius:20px ;border: 10px groove gray;border-style: outset"
"")
        self.third.setObjectName("third")
        self.forth = QtWidgets.QPushButton(self.centralwidget)
        self.forth.setGeometry(QtCore.QRect(440, 700, 481, 151))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 105, 118))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.forth.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.forth.setFont(font)
        self.forth.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forth.setAutoFillBackground(False)
        self.forth.setStyleSheet(" background-color:rgb(106, 105, 118); color:rgb(191, 190, 201);border-radius:20px ;border: 10px groove gray;border-style: outset"
"")
        self.forth.setObjectName("forth")
        self.L = QtWidgets.QLabel(self.centralwidget)
        self.L.setGeometry(QtCore.QRect(330, 10, 1261, 601))
        self.L.setStyleSheet("")
        self.L.setText("")
        self.L.setObjectName("L")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 630, 1330, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 190, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 391, 550))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1660, 0, 251, 561))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.first.raise_()
        self.second.raise_()
        self.third.raise_()
        self.L.raise_()
        self.label.raise_()
        self.forth.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.first.setText(_translate("MainWindow", "What are the special \n"
"features and functions?"))
        self.second.setText(_translate("MainWindow", "What are the materials\n"
" used for this costume?"))
        self.third.setText(_translate("MainWindow", "What are the weapons \n"
"that go with the\n"
" costume?"))
        self.forth.setText(_translate("MainWindow", "What is the name of\n"
" this costume?"))


        pix1 = QPixmap('../pythonProject/audio/1.png')
        self.label_2.setPixmap(pix1)
        pix2 = QPixmap('../pythonProject/audio/2.png')
        self.label_3.setPixmap(pix2)
##############
        self.movie = QMovie("../pythonProject/audio/1.gif")  # 替换为实际视频文件（GIF）的路径
        self.movie.setCacheMode(QMovie.CacheAll)
        self.L.setMovie(self.movie)
        self.movie.start()
        self.label.setText("What do you want to know?I am here to help you to learn about the costume?")
###############

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())





